In [1]:
rand(3,2)

NameError: name 'rand' is not defined

In [2]:
random.rand()

NameError: name 'random' is not defined

In [6]:
import numpy as np
np.random.rand(2)

array([0.84023558, 0.05911668])

In [7]:
np.random.rand(3)

array([0.71933007, 0.83992715, 0.45782343])

In [8]:
np.random.rand(2,3)

array([[0.07560751, 0.88307127, 0.89059614],
       [0.81568287, 0.67276802, 0.72120353]])

In [9]:
np.random.randint(2,3)

2

In [10]:
np.random.randint(2)

0

In [13]:
np.random.randint(2,10,3)

array([5, 2, 9])

In [14]:
np.random.randint(10,40,(10,10))

array([[26, 23, 33, 34, 28, 34, 24, 39, 27, 23],
       [28, 32, 32, 35, 15, 27, 33, 35, 21, 22],
       [31, 34, 23, 31, 28, 21, 27, 19, 15, 15],
       [36, 14, 11, 37, 18, 29, 24, 12, 33, 30],
       [33, 20, 37, 16, 28, 13, 23, 32, 14, 29],
       [25, 34, 12, 16, 17, 23, 35, 25, 31, 34],
       [11, 21, 27, 10, 20, 13, 26, 24, 38, 18],
       [15, 34, 28, 11, 12, 26, 18, 10, 12, 21],
       [25, 21, 17, 21, 29, 11, 32, 21, 26, 31],
       [14, 18, 14, 29, 28, 37, 11, 33, 32, 15]])

In [15]:
m=np.random.randint(10,40,(10,10))
m

array([[36, 23, 34, 36, 27, 22, 27, 20, 24, 16],
       [38, 16, 32, 12, 10, 19, 20, 31, 13, 12],
       [16, 25, 34, 25, 35, 33, 23, 14, 18, 31],
       [30, 29, 11, 33, 32, 33, 32, 16, 16, 33],
       [25, 25, 30, 33, 36, 28, 39, 21, 28, 39],
       [27, 12, 15, 31, 39, 11, 10, 27, 14, 35],
       [37, 19, 11, 12, 29, 37, 30, 25, 17, 21],
       [18, 14, 14, 17, 29, 28, 31, 22, 38, 13],
       [36, 16, 23, 25, 29, 26, 22, 27, 34, 16],
       [23, 39, 15, 36, 27, 38, 33, 29, 34, 15]])

In [19]:
arr = (1, 2, 3, 4, 5, 6)       # tuple
arr = np.array(arr)            # convert tuple → NumPy array
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [24]:
b=np.random.randint(10,20,(5,4))
b

array([[15, 12, 14, 10],
       [14, 10, 14, 12],
       [18, 17, 15, 16],
       [18, 11, 10, 17],
       [13, 17, 16, 15]])

In [25]:
b[1:4]

array([[14, 10, 14, 12],
       [18, 17, 15, 16],
       [18, 11, 10, 17]])

In [26]:
b[:-1]

array([[15, 12, 14, 10],
       [14, 10, 14, 12],
       [18, 17, 15, 16],
       [18, 11, 10, 17]])

In [27]:
b[-1:]

array([[13, 17, 16, 15]])

In [28]:
b

array([[15, 12, 14, 10],
       [14, 10, 14, 12],
       [18, 17, 15, 16],
       [18, 11, 10, 17],
       [13, 17, 16, 15]])

In [29]:
b[1,3]

12

In [30]:
arr

array([1, 2, 3, 4, 5, 6])

In [31]:
arr.max()

6

In [32]:
arr.min()

1

In [34]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [35]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
row=4
col=5

In [37]:
col

5

In [38]:
mat[row,col]

45

In [39]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [41]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [42]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [43]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [46]:
mat[1:2,2:4]

array([[12, 13]])

In [47]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

#masking

In [48]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [49]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])